# AlertManager configuration for notification routing
config:
  global:
    resolve_timeout: 5m
    slack_api_url: '${SLACK_WEBHOOK_URL}'
    smtp_smarthost: '${SMTP_HOST}:587'
    smtp_from: 'alerts@copycoder.com'
    smtp_auth_username: '${SMTP_USER}'
    smtp_auth_password: '${SMTP_PASSWORD}'

  route:
    group_by: ['alertname', 'cluster', 'service']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    receiver: 'slack-notifications'
    routes:
      - match:
          severity: critical
        receiver: 'pager-duty-critical'
      - match:
          severity: warning
        receiver: 'slack-notifications'

  receivers:
    - name: 'slack-notifications'
      slack_configs:
        - channel: '#alerts'
          title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
          text: "{{ range .Alerts }}*Alert:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n{{ end }}"
          send_resolved: true

    - name: 'pager-duty-critical'
      pagerduty_configs:
        - service_key: '${PAGERDUTY_SERVICE_KEY}'
          description: '{{ .CommonLabels.alertname }}'
          severity: critical
          client: 'AlertManager'
          client_url: '{{ template "pagerduty.default.clientURL" . }}' 